apiVersion: apps/v1
kind: Deployment
metadata:
  name: crisismapper-api
  namespace: crisismapper
  labels:
    app: crisismapper-api
    version: v2.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crisismapper-api
  template:
    metadata:
      labels:
        app: crisismapper-api
        version: v2.0.0
    spec:
      containers:
        - name: crisismapper-api
          image: crisismapper/enterprise:latest
          ports:
            - containerPort: 8000
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: crisismapper-secrets
                  key: jwt-secret
            - name: CRISIS_MAPPER_DEVICE
              value: "cuda"
            - name: CRISIS_MAPPER_DEBUG
              value: "false"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
              nvidia.com/gpu: 1
            limits:
              memory: "8Gi"
              cpu: "4000m"
              nvidia.com/gpu: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
            - name: models-volume
              mountPath: /app/models
            - name: results-volume
              mountPath: /app/results
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: crisismapper-data-pvc
        - name: models-volume
          persistentVolumeClaim:
            claimName: crisismapper-models-pvc
        - name: results-volume
          persistentVolumeClaim:
            claimName: crisismapper-results-pvc
      nodeSelector:
        accelerator: nvidia-tesla-gpu
